Server : Handler.cpp  Handler.h  HttpServer.cpp  HttpServer.h  HttpServerImpl.cpp  HttpServerImpl.h  main.cpp  rmtool.cpp  rmtool.h  type.h
	g++ -g Handler.cpp  Handler.h  HttpServer.cpp  HttpServer.h  HttpServerImpl.cpp  HttpServerImpl.h  main.cpp  rmtool.cpp  rmtool.h  type.h  -o Server -std=c++11 -lcurl -lglog -lpthread
clean :
	rm -f Server

